// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5RHQzQllPwd4ZLV--zAyvRGjRQjblfdI',
    appId: '1:423911772059:web:517204319777108441db3e',
    messagingSenderId: '423911772059',
    projectId: 'character-diagnosis-app',
    authDomain: 'character-diagnosis-app.firebaseapp.com',
    storageBucket: 'character-diagnosis-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOETFupOq4gfeoVwfJeAaRiAbabdU0C8E',
    appId: '1:423911772059:android:50366246ec2659b141db3e',
    messagingSenderId: '423911772059',
    projectId: 'character-diagnosis-app',
    storageBucket: 'character-diagnosis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbaNo0kIIHs-tDgtiiUeELnrwOVYxSYDc',
    appId: '1:423911772059:ios:8461d69c9e0fade041db3e',
    messagingSenderId: '423911772059',
    projectId: 'character-diagnosis-app',
    storageBucket: 'character-diagnosis-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbaNo0kIIHs-tDgtiiUeELnrwOVYxSYDc',
    appId: '1:423911772059:ios:8461d69c9e0fade041db3e',
    messagingSenderId: '423911772059',
    projectId: 'character-diagnosis-app',
    storageBucket: 'character-diagnosis-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5RHQzQllPwd4ZLV--zAyvRGjRQjblfdI',
    appId: '1:423911772059:web:4472442df9585a6741db3e',
    messagingSenderId: '423911772059',
    projectId: 'character-diagnosis-app',
    authDomain: 'character-diagnosis-app.firebaseapp.com',
    storageBucket: 'character-diagnosis-app.firebasestorage.app',
  );
}
